name: Crowdin Upload Sources
run-name: Triggered by ${{ github.actor }}

on:
  # push:
  #   # Run on pushes to any 'feature' branch
  #   branches:
  #     - 'main'
    # that changes the sources files in app/src/locales/en/*.po
    # or the Crowdin configuration file 
    # or the action itself
  workflow_dispatch:
    # paths:
    #   - app/src/locales/en/*.po
    #   - app/crowdin.yml
    #   - .github/workflows/crowdin-upload-sources.yml
    # types:
    #   - closed

jobs:
  upload-sources-to-crowdin:
    name: Upload Sources to Crowdin
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install crowdin
        run: |
          wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
          sudo dpkg -i crowdin.deb

      - name: Get branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Print current branch name
        run: echo "Current branch is ${{ steps.get_branch.outputs.branch_name }}"

      - name: Check if branch exists
        id: check_branch
        run: |
          if crowdin branch list --config app/crowdin.yml | grep -q "testing2"; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create branch
        if: steps.check_branch.outputs.branch_exists == 'false'
        run: crowdin branch add testing2 --config app/crowdin.yml
        # run: crowdin branch add ${{ github.head_ref }}
      
      - name: Upload sources
        uses: crowdin/github-action@v2
        timeout-minutes: 2
        with:
          config: 'app/crowdin.yml'
          upload_sources: true
          upload_translations: false
          download_translations: false
          create_pull_request: false
          crowdin_branch_name: 'testing2'
env:
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
