name: Merge Pull Request

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install crowdin
        run: |
          wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
          sudo dpkg -i crowdin.deb

      - name: Get branch name
        id: get_branch
        run: echo "branch_name=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT

      - name: Print branch name
        run: echo "Merged branch is ${{ steps.get_branch.outputs.branch_name }}"

      - name: Remove Crowdin branch
        run: |
          crowdin branch delete ${{ steps.get_branch.outputs.branch_name }} --config app/crowdin.yml
env:
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
